server:
  port: 9988
spring:
  datasource:
    url: jdbc:mysql://localhost/amoj?useUnicode=true&characterEncoding=UTF8&character_set_server=UTF8MB4&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    max-active: 40
    max-idle: 16
    min-idle: 16
    initial-size: 10
  mvc:
    static-path-pattern: /**
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
    typeAliasesPackage: amoj.entity
    mapperLocations: classpath:mapper/*.xml
    config-location: classpath:/mybatis-config.xml

baseweb:
  description:
    length: 128